/** IANA zones treated as India for consultation / ask-astrologer pricing. */
export const CONSULTATION_INDIA_TIMEZONES = [
  "Asia/Kolkata",
  "Asia/Calcutta",
  "IST",
] as const;

export const FOREIGN_LOCATION_HINTS = [
  "usa",
  "united states",
  "uk",
  "united kingdom",
  "canada",
  "australia",
  "uae",
  "dubai",
  "abu dhabi",
  "singapore",
  "malaysia",
  "germany",
  "france",
  "europe",
  "qatar",
  "saudi",
  "kuwait",
  "oman",
  "bahrain",
  "new zealand",
  "japan",
  "london",
  "new york",
  "california",
  "texas",
  "toronto",
  "sydney",
  "melbourne",
] as const;

export const INDIA_LOCATION_HINTS = [
  "india",
  "bharat",
  "hindustan",
  "tamil nadu",
  "tamilnadu",
  "kerala",
  "karnataka",
  "andhra pradesh",
  "andhra",
  "telangana",
  "maharashtra",
  "gujarat",
  "rajasthan",
  "punjab",
  "haryana",
  "uttar pradesh",
  "madhya pradesh",
  "bihar",
  "west bengal",
  "bengal",
  "odisha",
  "orissa",
  "assam",
  "goa",
  "himachal",
  "uttarakhand",
  "jharkhand",
  "chhattisgarh",
  "kashmir",
  "delhi",
  "puducherry",
  "pondicherry",
  "dindigul",
  "chennai",
  "madurai",
  "coimbatore",
  "trichy",
  "tiruchirappalli",
  "salem",
  "tiruppur",
  "erode",
  "vellore",
  "thoothukudi",
  "tirunelveli",
  "kanchipuram",
  "thanjavur",
  "nagarcoil",
  "nagercoil",
  "hosur",
  "bangalore",
  "bengaluru",
  "mysore",
  "mysuru",
  "mangaluru",
  "mangalore",
  "hubli",
  "belgaum",
  "hyderabad",
  "secunderabad",
  "visakhapatnam",
  "vijayawada",
  "guntur",
  "tirupati",
  "mumbai",
  "pune",
  "nagpur",
  "thane",
  "nashik",
  "aurangabad",
  "kolkata",
  "howrah",
  "ahmedabad",
  "surat",
  "vadodara",
  "rajkot",
  "jaipur",
  "jodhpur",
  "udaipur",
  "kota",
  "lucknow",
  "kanpur",
  "varanasi",
  "agra",
  "noida",
  "ghaziabad",
  "prayagraj",
  "patna",
  "gaya",
  "ranchi",
  "jamshedpur",
  "bhopal",
  "indore",
  "gwalior",
  "jabalpur",
  "raipur",
  "bilaspur",
  "chandigarh",
  "ludhiana",
  "amritsar",
  "jalandhar",
  "gurgaon",
  "gurugram",
  "faridabad",
  "panipat",
  "dehradun",
  "haridwar",
  "shimla",
  "srinagar",
  "jammu",
  "bhubaneswar",
  "cuttack",
  "guwahati",
  "kochi",
  "cochin",
  "trivandrum",
  "thiruvananthapuram",
  "kozhikode",
  "calicut",
  "thrissur",
  "kollam",
  "palakkad",
  "alappuzha",
  "kannur",
] as const;
