/** Ephemeris UI copy — merged into HOROSCOPE_SCREEN. */

export const HOROSCOPE_EPHEMERIS = {
  ephemerisTitlePrefix: "Ephemeris For",
  ephemerisTitleAt: "at",
  ephemerisModeDaily: "Daily",
  ephemerisModeMonthly: "Monthly",
  ephemerisColDate: "Date",
  ephemerisColMonth: "Month",
  ephemerisSortMonth: "Month",
  ephemerisLoading: "Loading ephemeris…",
  ephemerisError: "Could not load ephemeris",
  ephemerisMonths: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ] as const,
  ephemerisPlanets: [
    "Sun",
    "Moon",
    "Mars",
    "Mercury",
    "Jupiter",
    "Venus",
    "Saturn",
    "Rahu",
    "Ketu",
  ] as const,
  ephemerisPrevLabel: "Previous period",
  ephemerisNextLabel: "Next period",
  ephemerisPrevSymbol: "‹",
  ephemerisNextSymbol: "›",
  ephemerisUpdating: "Updating…",
  ephemerisMonthAria: "Select month",
  ephemerisYearAria: "Select year",
  /** Years shown in picker: current ± this span. */
  ephemerisYearSpan: 12,
} as const;
