/** Shadbala / Sthana / Kala copy — merged into HOROSCOPE_SCREEN. */

export const HOROSCOPE_SHADBALA = {
  colIshta: "Ishta",
  colKashta: "Kashta",
  colIshtaPhala: "Ishta Phala",
  colKashtaPhala: "Kashta Phala",
  colResidential: "Res.",
  colSthana: "Sthana",
  colDig: "Dig",
  colKala: "Kala",
  colDrik: "Drik",
  colChesta: "Chesta",
  colNaisargika: "Nais.",
  colShadbala: "Shad.",
  colRupa: "Rupa",
  colBalaPercent: "Bala%",
  colRank: "Rank",
  colOchcha: "Ochcha",
  colSaptavargaja: "Sapta.",
  colOjaYugma: "Oja.",
  colKendra: "Kendra",
  colDrekkana: "Drek.",
  colAbda: "Abda",
  colMasa: "Masa",
  colVara: "Vara",
  colHora: "Hora",
  colPaksha: "Paksha",
  colTribhaga: "Tri.",
  colNatonnata: "Nat.",
  colAyana: "Ayana",
  colYuddha: "Yuddha",
  colBhavaAdhipathi: "Adhipathi",
  colBhavaDig: "Bhava Dig",
  colBhavaDrishti: "Drishti",
  colBhavaBala: "Bhava Bala",
  shadbalaInnerShadbala: "Shadbala",
  shadbalaInnerSthana: "Sthana",
  shadbalaInnerKala: "Kala",
  shadbalaInnerBhava: "Bhava Bala",
  shadbalaBhavaUnavailable: "Could not load Bhava Bala",
  shadbalaSortLabel: "Sort",
  shadbalaSortRank: "Rank",
  shadbalaSortShadbala: "Shadbala",
  shadbalaSortBalaPercent: "Bala %",
  shadbalaSortPlanet: "Planet",
  shadbalaSortIshta: "Ishta",
  shadbalaSortKashta: "Kashta",
  shadbalaSortAsc: "Low → High",
  shadbalaSortDesc: "High → Low",
  sectionShadbalaTitle: "Shadbala",
} as const;
