/** Match making — user-facing copy (mirrors Flutter `matchMakingPage.dart`). */

export const MATCH_MAKING_SCREEN = {
  pageTitle: "Marriage Match Making",
  subtitle: "Check astrological compatibility for a perfect match",
  boySection: "Boy Details",
  girlSection: "Girl Details",
  boyNamePlaceholder: "Enter boy's name",
  girlNamePlaceholder: "Enter girl's name",
  calculateCta: "Calculate Match",
  loginTitle: "Sign in for match making",
  loginDescription: "Log in to calculate compatibility between two profiles.",
  loginCta: "Go to login",
  loadErrorTitle: "Could not load match data",
  submitCta: "Calculate Match",
  submitting: "Calculating…",
  tryAgainCta: "Try again",
  newMatchCta: "New match",
  viewSavedMatch: "View saved match",
  nameLabel: "Name",
  rashiFormLabel: "Rasi (moon sign)",
  nakshatraFormLabel: "Nakshatra",
  selectPlaceholder: "Select…",
  resultTitle: "Marriage Match Making",
  boyNameLabel: "Boy Name",
  girlNameLabel: "Girl Name",
  rasiLabel: "Rasi",
  nakshatraLabel: "Nakshatram",
  totalCompatibilityScore: "Total Compatibility Score",
  kutaColumn: "Kuta",
  gainedColumn: "Gained",
  maxColumn: "Max",
  presentBadge: "Present",
  absentBadge: "Absent",
  expertConnectCta: "Expert Connect",
  regenerateCta: "Regenerate",
  scoreLabel: "Score",
  generalLabel: "Summary",
  kutaLabel: "Gun Milan",
  downloadPdfCta: "Download PDF",
  sharePdfError: "Could not download PDF. Please try again.",
  noMatchYet:
    "No saved match yet. Enter details below to generate your compatibility report.",
} as const;
