/** Muhurtha feature copy — keep strings out of TSX. */

export const MUHURTHA_SCREEN = {
  headerTitle: "Event Planner (Muhurtha)",
  formTitle: "Plan an auspicious time",
  formSubtitle:
    "Select a life event and start date. We scan the next 7 days to find auspicious dates for you using your birth chart and panchang.",
  eventLabel: "Event type",
  startDateLabel: "Start date",
  startDateHint: "Searching the next 7 days from this date",
  locationLabel: "Location",
  locationFromProfile: "From your profile",
  findCta: "Find Auspicious Dates",
  loginTitle: "Sign in to find Event Planner",
  loginDescription: "Use your email or mobile OTP on the login screen.",
  loginCta: "Go to login",
  premiumTitle: "Event Planner is a premium feature",
  premiumDescription:
    "Subscribe to unlock personalized auspicious dates for your life events. ",
  upgradeCta: "Upgrade Now",
  loadErrorTitle: "Could not load Event Planner",
  loadErrorFallback: "Failed to find auspicious dates.",
  tryAgainCta: "Try again",
  resultsTitle: "Event Planner results",
  backToFormCta: "New search",
  emptyTitle: "No auspicious dates found",
  emptyDescription:
    "No days in this window passed all Vedic filters for your event. Try another start date or event.",
  dateColumn: "Date",
  statusColumn: "Status",
  detailsColumn: "Details",
  suitableLabel: "Suitable",
  notSuitableLabel: "Not suitable",
  periodMorning: "Morning",
  periodEvening: "Evening",
  periodFullDay: "Full day",
  locationPlaceholder: "Search city or place",
  locationRequired: "Location is required",
  reasonInfoAria: "Why this day is not suitable",
  windowColumn: "Auspicious window",
  panchangCta: "Find Event Planner for your event",
  panchangCtaHint: "Personalized 7-day scan for life events",
  detailLabels: {
    weekday: "Weekday",
    nakshatra: "Nakshatra",
    thithi: "Thithi",
    tharaBala: "Thara Bala",
    chandraBala: "Chandra Bala",
    yoga: "Amirthathi Yoga",
  },
  expandAria: "Show day details",
  collapseAria: "Hide day details",
  askAstrologerCta: "Ask Astrologer",
  eventPlanAccordionLabel: "Your event plan",
  eventPlanAccordionExpand: "View event plan",
  eventPlanAccordionCollapse: "Hide event plan",
} as const;
