export const SETTINGS_SUBSCRIPTIONS_COPY = {
  pageTitle: "Subscription",
  loadFailed: "Could not load subscription details.",
  plansFailed: "Could not load plans.",
  activeLabel: "Current plan",
  daysRemaining: "days remaining",
  daysLeft: "days left",
  tryPremium: "Try Premium Plan",
  subscribeCta: "Subscribe",
  upgradeCta: "Upgrade Plan",
  currentPlan: "Your Current Plan",
  planLabel: "Plan",
  recommended: "Recommended",
  processing: "Processing…",
  paymentFailed: "Payment failed. Please try again.",
  paymentSuccess: "Subscription activated. Enjoy premium features!",
  noPlans: "No plans available for your region.",
  premiumFeatures: "Premium unlocks daily, weekly, and yearly prediction notifications.",
} as const;
